version: "3.9"

services:
  elasticsearch:
    image: elasticsearch:7.17.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
  kibana:
    image: kibana:7.17.2
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
  logstash:
    build:
      context: .
      dockerfile: Dockerfile.logstash
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044"
  logger:
    build:
      context: .
      dockerfile: Dockerfile.log_generator
    depends_on:
      - logstash
